#deps
./main.o: $(INCDIR)/scc/scc/mach.h
./main.o: ./ld.h
./pass1.o: $(INCDIR)/scc/scc/ar.h
./pass1.o: $(INCDIR)/scc/scc/mach.h
./pass1.o: $(INCDIR)/scc/scc/scc.h
./pass1.o: ./ld.h
./pass2.o: $(INCDIR)/scc/scc/mach.h
./pass2.o: ./ld.h
./pass3.o: $(INCDIR)/scc/scc/mach.h
./pass3.o: ./ld.h
./pass4.o: $(INCDIR)/scc/scc/mach.h
./pass4.o: ./ld.h
./pass5.o: $(INCDIR)/scc/scc/mach.h
./pass5.o: ./ld.h
./section.o: $(INCDIR)/scc/scc/mach.h
./section.o: $(INCDIR)/scc/scc/scc.h
./section.o: ./ld.h
./symbol.o: $(INCDIR)/scc/scc/mach.h
./symbol.o: $(INCDIR)/scc/scc/scc.h
./symbol.o: ./ld.h
