#deps
./coff32.o: $(INCDIR)/scc/scc/mach.h
./coff32.o: ./../libmach.h
./coff32.o: ./coff32.h
./coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32del.o: ./../libmach.h
./coff32del.o: ./coff32.h
./coff32getidx.o: $(INCDIR)/scc/scc/mach.h
./coff32getidx.o: ./../libmach.h
./coff32getidx.o: ./coff32.h
./coff32getsec.o: $(INCDIR)/scc/scc/mach.h
./coff32getsec.o: ./../libmach.h
./coff32getsec.o: ./coff32.h
./coff32getsym.o: $(INCDIR)/scc/scc/mach.h
./coff32getsym.o: ./../libmach.h
./coff32getsym.o: ./coff32.h
./coff32loadmap.o: $(INCDIR)/scc/scc/mach.h
./coff32loadmap.o: ./../libmach.h
./coff32loadmap.o: ./coff32.h
./coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32new.o: ./../libmach.h
./coff32new.o: ./coff32.h
./coff32pc2line.o: $(INCDIR)/scc/scc/mach.h
./coff32pc2line.o: ./../libmach.h
./coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32probe.o: ./../libmach.h
./coff32probe.o: ./coff32.h
./coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32read.o: ./../libmach.h
./coff32read.o: ./coff32.h
./coff32setidx.o: $(INCDIR)/scc/scc/mach.h
./coff32setidx.o: ./../libmach.h
./coff32setidx.o: ./coff32.h
./coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32strip.o: ./../libmach.h
./coff32strip.o: ./coff32.h
./coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32write.o: ./../libmach.h
./coff32write.o: ./coff32.h
./coff32xgetidx.o: $(INCDIR)/scc/scc/cstd.h
./coff32xgetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32xgetidx.o: ./../libmach.h
./coff32xgetidx.o: ./coff32.h
./coff32xsetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32xsetidx.o: ./../libmach.h
