#!/bin/sh

set -e

(echo '/^#deps/;$c'
echo '#deps'

for i in `find . -name '*.c'`
do
	file=`basename $i | sed 's/\.c$/.o/'`
	dir=`dirname $i`

	sed -n "/^#include / {
		s///
		s@\"\(.*\)\"@$dir/$file: $dir/\1@p
		s@<\(scc/.*\)>@$dir/$file: \$(INCDIR)/scc/\1@p
	}" $i
done | LC_ALL=C sort -s

echo .
echo w) | ed -s deps.mk
