#!/bin/sh

set -e

usage()
{
	echo usage: mklib [-o library] file ... >&2
	exit 1
}

for i
do
	case "$1" in
	-o)
		out=$2
		shift 2
		;;
	--)
		shift
		break;
		;;
	-*)
		usage
		;;
	esac
done

case $# in
0)
	usage
	;;
esac

lib=${out-a.out}

if ! test -f $lib
then
	${AR:-ar} $ARCHIVEFLAGS -qv $lib $(lorder $@ | tsort)
else
	${AR:-ar} $ARCHIVEFLAGS -ruv $lib $(lorder $@ | tsort)
fi

${RL:-ranlib} $RLFLAGS $lib
