#deps
./amd64-sysv.o: $(INCDIR)/scc/scc/scc.h
./amd64-sysv.o: ./cc1.h
./arch.o: $(INCDIR)/scc/scc/scc.h
./arch.o: ./cc1.h
./arm64-sysv.o: $(INCDIR)/scc/scc/scc.h
./arm64-sysv.o: ./cc1.h
./builtin.o: $(INCDIR)/scc/scc/scc.h
./builtin.o: ./cc1.h
./code.o: $(INCDIR)/scc/scc/scc.h
./code.o: ./cc1.h
./cpp.o: $(INCDIR)/scc/scc/cstd.h
./cpp.o: $(INCDIR)/scc/scc/scc.h
./cpp.o: ./cc1.h
./decl.o: $(INCDIR)/scc/scc/cstd.h
./decl.o: $(INCDIR)/scc/scc/scc.h
./decl.o: ./cc1.h
./error.o: $(INCDIR)/scc/scc/scc.h
./error.o: ./cc1.h
./expr.o: $(INCDIR)/scc/scc/cstd.h
./expr.o: $(INCDIR)/scc/scc/scc.h
./expr.o: ./cc1.h
./fold.o: $(INCDIR)/scc/scc/scc.h
./fold.o: ./cc1.h
./i386-sysv.o: $(INCDIR)/scc/scc/scc.h
./i386-sysv.o: ./cc1.h
./init.o: $(INCDIR)/scc/scc/cstd.h
./init.o: $(INCDIR)/scc/scc/scc.h
./init.o: ./cc1.h
./lex.o: $(INCDIR)/scc/scc/cstd.h
./lex.o: $(INCDIR)/scc/scc/scc.h
./lex.o: ./cc1.h
./main.o: $(INCDIR)/scc/scc/arg.h
./main.o: $(INCDIR)/scc/scc/scc.h
./main.o: ./cc1.h
./stmt.o: $(INCDIR)/scc/scc/cstd.h
./stmt.o: $(INCDIR)/scc/scc/scc.h
./stmt.o: ./cc1.h
./symbol.o: $(INCDIR)/scc/scc/cstd.h
./symbol.o: $(INCDIR)/scc/scc/scc.h
./symbol.o: ./cc1.h
./types.o: $(INCDIR)/scc/scc/cstd.h
./types.o: $(INCDIR)/scc/scc/scc.h
./types.o: ./cc1.h
./z80-scc.o: $(INCDIR)/scc/scc/scc.h
./z80-scc.o: ./cc1.h
