#deps
./expr.o: $(INCDIR)/scc/scc/scc.h
./expr.o: ./as.h
./ins.o: $(INCDIR)/scc/scc/scc.h
./ins.o: ./as.h
./main.o: $(INCDIR)/scc/scc/arg.h
./main.o: $(INCDIR)/scc/scc/scc.h
./main.o: ./as.h
./parser.o: $(INCDIR)/scc/scc/cstd.h
./parser.o: $(INCDIR)/scc/scc/scc.h
./parser.o: ./as.h
./symbol.o: $(INCDIR)/scc/scc/scc.h
./symbol.o: ./as.h
./target/powerpc/ins.o: $(INCDIR)/scc/scc/scc.h
./target/powerpc/ins.o: ./target/powerpc/../../as.h
./target/powerpc/ins.o: ./target/powerpc/proc.h
./target/powerpc/powerpc.o: $(INCDIR)/scc/scc/scc.h
./target/powerpc/powerpc.o: ./target/powerpc/../../as.h
./target/powerpc/powerpc.o: ./target/powerpc/proc.h
./target/powerpc/powerpc64.o: $(INCDIR)/scc/scc/scc.h
./target/powerpc/powerpc64.o: ./target/powerpc/../../as.h
./target/powerpc/powerpc64.o: ./target/powerpc/proc.h
./target/powerpc/powerpc64tbl.o: $(INCDIR)/scc/scc/scc.h
./target/powerpc/powerpc64tbl.o: ./target/powerpc/../../as.h
./target/powerpc/powerpc64tbl.o: ./target/powerpc/../powerpc/proc.h
./target/powerpc/powerpctbl.o: $(INCDIR)/scc/scc/scc.h
./target/powerpc/powerpctbl.o: ./target/powerpc/../../as.h
./target/powerpc/powerpctbl.o: ./target/powerpc/../powerpc/proc.h
./target/x80/ins.o: $(INCDIR)/scc/scc/scc.h
./target/x80/ins.o: ./target/x80/../../as.h
./target/x80/ins.o: ./target/x80/proc.h
./target/x80/z80.o: $(INCDIR)/scc/scc/scc.h
./target/x80/z80.o: ./target/x80/../../as.h
./target/x80/z80.o: ./target/x80/../x80/proc.h
./target/x80/z80tbl.o: $(INCDIR)/scc/scc/scc.h
./target/x80/z80tbl.o: ./target/x80/../../as.h
./target/x80/z80tbl.o: ./target/x80/../x80/proc.h
./target/x86/amd64.o: $(INCDIR)/scc/scc/scc.h
./target/x86/amd64.o: ./target/x86/../../as.h
./target/x86/amd64tbl.o: $(INCDIR)/scc/scc/scc.h
./target/x86/amd64tbl.o: ./target/x86/../../as.h
./target/x86/amd64tbl.o: ./target/x86/../x86/proc.h
./target/x86/i286.o: $(INCDIR)/scc/scc/scc.h
./target/x86/i286.o: ./target/x86/../../as.h
./target/x86/i286.o: ./target/x86/../x86/proc.h
./target/x86/i286tbl.o: $(INCDIR)/scc/scc/scc.h
./target/x86/i286tbl.o: ./target/x86/../../as.h
./target/x86/i286tbl.o: ./target/x86/../x86/proc.h
./target/x86/i386.o: $(INCDIR)/scc/scc/scc.h
./target/x86/i386.o: ./target/x86/../../as.h
./target/x86/i386.o: ./target/x86/../x86/proc.h
./target/x86/i386tbl.o: $(INCDIR)/scc/scc/scc.h
./target/x86/i386tbl.o: ./target/x86/../../as.h
./target/x86/i386tbl.o: ./target/x86/../x86/proc.h
./target/x86/ins.o: $(INCDIR)/scc/scc/scc.h
./target/x86/ins.o: ./target/x86/../../as.h
./target/x86/ins.o: ./target/x86/proc.h
