#deps
./__getc.o: ./../libc.h
./__getc.o: ./../syscall.h
./__putc.o: ./../libc.h
./_allocbuf.o: ./../libc.h
./_flsbuf.o: ./../libc.h
./_flsbuf.o: ./../syscall.h
./_fpopen.o: ./../libc.h
./_fpopen.o: ./../syscall.h
./fclose.o: ./../libc.h
./fclose.o: ./../syscall.h
./fopen.o: ./../libc.h
./fopen.o: ./../syscall.h
./freopen.o: ./../libc.h
./freopen.o: ./../syscall.h
./fseek.o: ./../libc.h
./fseek.o: ./../syscall.h
./ftell.o: ./../syscall.h
./setvbuf.o: ./../libc.h
./tmpnam.o: ./../syscall.h
