#deps
./darwin/_tzone.o: ./darwin/../../posix/_tzone.c
./darwin/getenv.o: ./darwin/../../posix/getenv.c
./darwin/raise.o: ./darwin/../../posix/raise.c
./darwin/signal.o: ./darwin/../../posix/signal.c
./darwin/time.o: ./darwin/../../posix/time.c
./dragonfly/_getheap.o: ./dragonfly/../../posix/_getheap.c
./dragonfly/_tzone.o: ./dragonfly/../../posix/_tzone.c
./dragonfly/getenv.o: ./dragonfly/../../posix/getenv.c
./dragonfly/raise.o: ./dragonfly/../../posix/raise.c
./dragonfly/signal.o: ./dragonfly/../../posix/signal.c
./dragonfly/time.o: ./dragonfly/../../posix/time.c
./linux/_getheap.o: ./linux/../../linux/_getheap.c
./linux/_tzone.o: ./linux/../../posix/_tzone.c
./linux/getenv.o: ./linux/../../posix/getenv.c
./linux/raise.o: ./linux/../../posix/raise.c
./linux/signal.o: ./linux/../../posix/signal.c
./linux/time.o: ./linux/../../posix/time.c
./memchr.o: ./../../string/memchr.c
./memcmp.o: ./../../string/memcmp.c
./memmove.o: ./../../string/memmove.c
./memset.o: ./../../string/memset.c
./netbsd/_getheap.o: ./netbsd/../../posix/_getheap.c
./netbsd/_tzone.o: ./netbsd/../../posix/_tzone.c
./netbsd/getenv.o: ./netbsd/../../posix/getenv.c
./netbsd/raise.o: ./netbsd/../../posix/raise.c
./netbsd/signal.o: ./netbsd/../../posix/signal.c
./netbsd/time.o: ./netbsd/../../posix/time.c
./openbsd/_getheap.o: ./openbsd/../../posix/_getheap.c
./openbsd/_tzone.o: ./openbsd/../../posix/_tzone.c
./openbsd/getenv.o: ./openbsd/../../posix/getenv.c
./openbsd/raise.o: ./openbsd/../../posix/raise.c
./openbsd/signal.o: ./openbsd/../../posix/signal.c
./openbsd/time.o: ./openbsd/../../posix/time.c
