#deps
./archive.o: $(INCDIR)/scc/scc/ar.h
./archive.o: $(INCDIR)/scc/scc/mach.h
./archive.o: ./libmach.h
./armember.o: $(INCDIR)/scc/scc/ar.h
./armember.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32.o: ./coff32/../libmach.h
./coff32/coff32.o: ./coff32/coff32.h
./coff32/coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32del.o: ./coff32/../libmach.h
./coff32/coff32del.o: ./coff32/coff32.h
./coff32/coff32getidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getidx.o: ./coff32/../libmach.h
./coff32/coff32getidx.o: ./coff32/coff32.h
./coff32/coff32getsec.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getsec.o: ./coff32/../libmach.h
./coff32/coff32getsec.o: ./coff32/coff32.h
./coff32/coff32getsym.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getsym.o: ./coff32/../libmach.h
./coff32/coff32getsym.o: ./coff32/coff32.h
./coff32/coff32loadmap.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32loadmap.o: ./coff32/../libmach.h
./coff32/coff32loadmap.o: ./coff32/coff32.h
./coff32/coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32new.o: ./coff32/../libmach.h
./coff32/coff32new.o: ./coff32/coff32.h
./coff32/coff32pc2line.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32pc2line.o: ./coff32/../libmach.h
./coff32/coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32probe.o: ./coff32/../libmach.h
./coff32/coff32probe.o: ./coff32/coff32.h
./coff32/coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32read.o: ./coff32/../libmach.h
./coff32/coff32read.o: ./coff32/coff32.h
./coff32/coff32setidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32setidx.o: ./coff32/../libmach.h
./coff32/coff32setidx.o: ./coff32/coff32.h
./coff32/coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32strip.o: ./coff32/../libmach.h
./coff32/coff32strip.o: ./coff32/coff32.h
./coff32/coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32write.o: ./coff32/../libmach.h
./coff32/coff32write.o: ./coff32/coff32.h
./coff32/coff32xgetidx.o: $(INCDIR)/scc/scc/cstd.h
./coff32/coff32xgetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32xgetidx.o: ./coff32/../libmach.h
./coff32/coff32xgetidx.o: ./coff32/coff32.h
./coff32/coff32xsetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32xsetidx.o: ./coff32/../libmach.h
./delobj.o: $(INCDIR)/scc/scc/mach.h
./delobj.o: ./libmach.h
./findsec.o: $(INCDIR)/scc/scc/mach.h
./findsec.o: ./libmach.h
./getindex.o: $(INCDIR)/scc/scc/mach.h
./getindex.o: ./libmach.h
./getsec.o: $(INCDIR)/scc/scc/mach.h
./getsec.o: ./libmach.h
./getsym.o: $(INCDIR)/scc/scc/mach.h
./getsym.o: ./libmach.h
./loadmap.o: $(INCDIR)/scc/scc/mach.h
./loadmap.o: ./libmach.h
./mach.o: $(INCDIR)/scc/scc/mach.h
./mach.o: ./libmach.h
./newmap.o: $(INCDIR)/scc/scc/mach.h
./newmap.o: ./libmach.h
./newobj.o: $(INCDIR)/scc/scc/mach.h
./newobj.o: ./libmach.h
./objpos.o: $(INCDIR)/scc/scc/mach.h
./objpos.o: ./libmach.h
./objtype.o: $(INCDIR)/scc/scc/mach.h
./objtype.o: ./libmach.h
./pack.o: $(INCDIR)/scc/scc/mach.h
./pack.o: ./libmach.h
./pc2line.o: $(INCDIR)/scc/scc/mach.h
./pc2line.o: ./libmach.h
./readobj.o: $(INCDIR)/scc/scc/mach.h
./readobj.o: ./libmach.h
./rebase.o: $(INCDIR)/scc/scc/mach.h
./rebase.o: ./libmach.h
./setindex.o: $(INCDIR)/scc/scc/mach.h
./setindex.o: ./libmach.h
./setmap.o: $(INCDIR)/scc/scc/mach.h
./setmap.o: ./libmach.h
./strip.o: $(INCDIR)/scc/scc/mach.h
./strip.o: ./libmach.h
./unpack.o: $(INCDIR)/scc/scc/mach.h
./unpack.o: ./libmach.h
./writeobj.o: $(INCDIR)/scc/scc/mach.h
./writeobj.o: ./libmach.h
