.Dd March 15, 2020
.Dt SFEED_MBOX 1
.Os
.Sh NAME
.Nm sfeed_mbox
.Nd format feed data to mboxrd
.Sh SYNOPSIS
.Nm
.Op Ar file...
.Sh DESCRIPTION
.Nm
formats feed data (TSV) from
.Xr sfeed 1
from stdin or
.Ar file
to stdout in the mboxrd format.
If one or more
.Ar file
are specified, the basename of the
.Ar file
is used as the feed name in the output.
If no
.Ar file
parameters are specified and so the data is read from stdin the feed name
is empty.
The mbox data can be further processed by tools like
.Xr procmail 1
or
.Xr fdm 1
for example.
See the README file for some useful examples.
.Sh CUSTOM HEADERS
To make further filtering simpler some custom headers are set:
.Bl -tag -width Ds
.It X-Feedname
The feedname (as set in sfeedrc).
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr fdm 1 ,
.Xr procmail 1 ,
.Xr sfeed 1 ,
.Xr sfeed 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
