.Dd July 31, 2021
.Dt SFEED_FRAMES 1
.Os
.Sh NAME
.Nm sfeed_frames
.Nd format feed data to HTML with frames
.Sh SYNOPSIS
.Nm
.Op Ar
.Sh DESCRIPTION
.Nm
formats feed data (TSV) from
.Xr sfeed 1
from stdin or for each
.Ar file
to HTML.
It writes HTML files for the frameset to the current directory.
If no
.Ar file
arguments are specified and so the data is read from stdin then the menu.html
file is not written.
.Pp
Items with a timestamp from the last day compared to the system time at the
time of formatting are counted and marked as new.
Items are marked as new using a bold markup.
This value might be overridden through environment variables.
.Pp
There is an example style.css stylesheet file included in the distribution.
.Sh FILES WRITTEN
.Bl -tag -width 13n
.It index.html
The main HTML file referencing the files for the frames: items.html and
menu.html.
.It items.html
The HTML file of the items frame which contains all the item links to the
feeds.
.It menu.html
The HTML file of the menu frame which contains navigation "anchor" links (like
"#feedname") to the feed names in items.html.
.El
.Sh ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It Ev SFEED_NEW_AGE
Overwrite the maximum age in seconds to mark feeds as new.
By default this is 86400, which equals one day.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Bd -literal
sfeed_frames ~/.sfeed/feeds/*
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed_plain 1 ,
.Xr sfeed 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
