.Dd May 14, 2022
.Dt SFEED_PLAIN 1
.Os
.Sh NAME
.Nm sfeed_plain
.Nd format feed data to a plain-text list
.Sh SYNOPSIS
.Nm
.Op Ar
.Sh DESCRIPTION
.Nm
formats feed data (TSV) from
.Xr sfeed 1
from stdin or for each
.Ar file
to stdout as a plain-text list.
If one or more
.Ar file
arguments are specified then the basename of the
.Ar file
is used as the feed name in the output.
If no
.Ar file
arguments are specified and so the data is read from stdin then the feed name
is empty.
.Pp
Items with a timestamp from the last day compared to the system time at the
time of formatting are marked as new.
This value might be overridden through environment variables.
Items are marked as new with the prefix "N" at the start of the line.
.Pp
.Nm
aligns the output.
It shows a maximum of 70 column-wide characters for the title and outputs
an ellipsis symbol if the title is longer and truncated.
Make sure the environment variable
.Ev LC_CTYPE
is set to a UTF-8 locale, so it can determine the proper column-width
per rune, using
.Xr mbtowc 3
and
.Xr wcwidth 3 .
.Sh ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It Ev SFEED_NEW_AGE
Overwrite the maximum age in seconds to mark feeds as new.
By default this is 86400, which equals one day.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Bd -literal
curl -s 'https://codemadness.org/atom.xml' | sfeed | sfeed_plain
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
