.Dd March 15, 2020
.Dt SFEED_OPML_IMPORT 1
.Os
.Sh NAME
.Nm sfeed_opml_import
.Nd generate a sfeedrc config file from an OPML file
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads the OPML XML data from stdin and writes the config file text to stdout.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr sfeed_update 1 ,
.Xr sfeedrc 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
