.Dd January 7, 2023
.Dt SFEED 5
.Os
.Sh NAME
.Nm sfeed
.Nd feed format
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Xr sfeed 1
writes the feed data in a TAB-separated format to stdout.
.Sh TAB-SEPARATED FORMAT FIELDS
The items are output per line in a TAB-separated format.
.Pp
For the fields title, id and author each whitespace character is replaced by a
SPACE character.
Control characters are removed.
.Pp
The content field can contain newlines and these are escaped.
TABs, newlines and '\e' are escaped with '\e', so it becomes: '\et', '\en'
and '\e\e'.
Other whitespace characters except spaces are removed.
Control characters are removed.
.Pp
The order and content of the fields are:
.Bl -tag -width 15n
.It 1. timestamp
UNIX timestamp in UTC+0, empty if missing or on a parse failure.
.It 2. title
Title text, HTML code in titles is ignored and is treated as plain-text.
.It 3. link
Link
.It 4. content
Content, can have plain-text or HTML code depending on the content-type field.
.It 5. content-type
"html" or "plain" if it has content.
.It 6. id
RSS item GUID or Atom id.
.It 7. author
Item, first author.
.It 8. enclosure
Item, first enclosure.
.It 9. category
Item, categories, multiple values are separated by the '|' character.
.El
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_plain 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
