.Dd July 31, 2021
.Dt SFEED_HTML 1
.Os
.Sh NAME
.Nm sfeed_html
.Nd format feed data to HTML
.Sh SYNOPSIS
.Nm
.Op Ar
.Sh DESCRIPTION
.Nm
formats feed data (TSV) from
.Xr sfeed 1
from stdin or for each
.Ar file
to stdout in HTML.
If one or more
.Ar file
arguments are specified then the basename of the
.Ar file
is used as the feed name in the output.
If no
.Ar file
arguments are specified and so the data is read from stdin then the feed name
is empty.
.Pp
Items with a timestamp from the last day compared to the system time at the
time of formatting are counted and marked as new.
This value might be overridden through environment variables.
Items are marked as new using a bold markup.
.Pp
There is an example style.css stylesheet file included in the distribution.
.Sh ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It Ev SFEED_NEW_AGE
Overwrite the maximum age in seconds to mark feeds as new.
By default this is 86400, which equals one day.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Bd -literal
sfeed_html ~/.sfeed/feeds/*
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_frames 1 ,
.Xr sfeed_plain 1 ,
.Xr sfeed 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
