.Dd December 15, 2022
.Dt SFEED_UPDATE 1
.Os
.Sh NAME
.Nm sfeed_update
.Nd update feeds and merge with old feeds
.Sh SYNOPSIS
.Nm
.Op Ar sfeedrc
.Sh DESCRIPTION
.Nm
writes TAB-separated feed files and merges new items with the items in any
existing files.
The items are stored as one file per feed in the directory
.Pa $HOME/.sfeed/feeds
by default.
The directory can be changed in the
.Xr sfeedrc 5
file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Ar sfeedrc
Config file.
The default is
.Pa $HOME/.sfeed/sfeedrc .
.El
.Sh FILES READ
.Bl -tag -width Ds
.It Ar sfeedrc
This file is evaluated as a shellscript in
.Nm .
See also the
.Xr sfeedrc 5
man page for a detailed description of the format and an example file.
.El
.Sh FILES WRITTEN
.Bl -tag -width Ds
.It feedname
TAB-separated
.Xr sfeed 5
format containing all items per feed.
The
.Nm
script merges new items with this file.
The feed name cannot contain the '/' character because it is a path separator,
they will be replaced with '_'.
.El
.Sh ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It SFEED_UPDATE_INCLUDE
When set to "1"
.Nm
can be sourced as a script, but it won't run the
.Fn main
entry-point.
.El
.Sh LOGGING
When processing a feed it will log failures to stderr and non-failures to
stdout in the format:
.Bd -literal
[HH:MM:SS] feedname message
.Ed
.Sh EXIT STATUS
.Ex -std
If any of the feeds failed to update then the exit status is non-zero.
.Sh EXAMPLES
To update your feeds and format them in various formats:
.Bd -literal
# Update feeds
sfeed_update "configfile"
# Format to a plain-text list
sfeed_plain ~/.sfeed/feeds/* > ~/.sfeed/feeds.txt
# Format to HTML
sfeed_html ~/.sfeed/feeds/* > ~/.sfeed/feeds.html
# Format to HTML with frames
mkdir -p somedir && cd somedir && sfeed_frames ~/.sfeed/feeds/*
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_frames 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed_plain 1 ,
.Xr sh 1 ,
.Xr sfeed 5 ,
.Xr sfeedrc 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
