#!/bin/sh

trap 'r=$?; rm -f $$.tmp; exit $r' EXIT HUP INT QUIT TERM

awk '
/^#define[ \t]*E/{
	str = ""
	for (i = 5; i < NF; i++)
		str = str " " $i
	sub(/^ /, "", str)
	errstr[$2] = str
	if ($3 > max)
		max = $3;
}

END {
	print "#include <errno.h>\n"
	print "char *const _sys_errlist[] = {"
	for (i in errstr)
		printf "\t%-20.20s = \"%s\",\n", "[" i "]", errstr[i]

	print "};"
	print "const int _sys_nerr =", max";"
}' $@ > $$.tmp && mv $$.tmp _sys_errlist.c
