.POSIX:

PROJECTDIR = ..
include $(PROJECTDIR)/scripts/rules.mk

DIRS=ar/execute \
     nm/execute \
     as/execute \
     ld/execute \
     size/execute \
     strip/execute \
     libc/execute \
     cc/execute cc/error

all clean:
	$(FORALL)
