.Dd August 02, 2020
.Dt SFEED_CONTENT 1
.Os
.Sh NAME
.Nm sfeed_content
.Nd view RSS/Atom content
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
expects to receive a TSV line from stdin in the
.Xr sfeed 5
format.
By default it will format the data to a readable plain-text format and use the
pager.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr awk 1 ,
.Xr lynx 1 ,
.Xr sfeed_curses 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
